common: &COMMON
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  min_messages: warning

development:
  <<: *COMMON
  database: pingpong_development

test: &TEST
  <<: *COMMON
  database: pingpong_test<%= ENV['TEST_ENV_NUMBER'] %>

cucumber:
  <<: *TEST
