#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: dormie
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: dormie-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo: 
  app: dormie-demo
  config: *default
